version: '3.9'

services:
  backend: 
    build: .
    ports:
      - 5000:80
    environment:
      - MONGO_URL=mongodb://mongodb:27017
  # smartfox:
  #   image: timlien/docker-smartfox
  #   ports:
  #     - 8080:8080
  #     - 9933:9933
  #     - 8787:8787
  #     - 5000:5000
  mongodb:
    image: mongo:latest
    container_name: docker-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_vol:/data/db

volumes:
  mongo_vol:
