version: '3.9'

services:
  backend: 
    build: .
    ports:
      - 5000:80
    environment:
      - MONGO_URL=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    container_name: docker-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_vol:/data/db

volumes:
  mongo_vol:
